[book]
title = "F.A.D.E. RPG System Reference Document"
authors = ["X Kirby"]
language = "en"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/XKirby/F.A.D.E.-RPG-SRD"

[output.html.fold]
enable = true
level = 0
